# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'WiFi-USB' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WiFi-USB
  pod 'SwiftWebSocket', '~> 2.6'
end

target 'WK-WiFi-USB' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WK-WiFi-USB
end

target 'WK-WiFi-USB Extension' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WK-WiFi-USB Extension
end
